let a=document.getElementById('id1')
a.insertAdjacentHTML('beforeend','<p>BEFOREEND</p>')
a.insertAdjacentHTML('beforebegin','<p>BEFOREBEGIN</p>')
a.insertAdjacentHTML('afterend','<p>AFTEREND</p>')
a.insertAdjacentHTML('afterbegin','<p>AFTERBEGIN</p>')